### PR TITLE
Upgrade Prokka to 1.14.0

### PR DESCRIPTION
**Pull request by xlinxlin**
Upgrade Prokka to 1.14.0

### CODE REVIEW

**Comment by drpatelh** [comment]
Amazing! Thanks @xlinxlin !

So the automated tests are failing for two reasons:
1. Some of the dependencies in the `environment.yml` dont have a pinned version number i.e. `tqdm`, `jinja2` and `plotly`
2. The pipeline tests are still using the old `Docker` container which you reported as not working. We will need to merge this PR for it to be rebuilt.

It would be great if you can try and pin the software versions in (1) and try and build the environment locally, and test the pipeline. When that is all working we can merge this PR because the pipeline tests are going to fail anyway. Hopefully, you can then run the pipeline with the `-r dev` parameter and things should be working again :+1:

**Comment by xlinxlin** [comment]
Hi @drpatelh actually after I met the error I have made a conda environment on our server and ran the pipeline within it without any problem. In the attachment you can find the YML file of this environment, but I don't find `tqdm` and `plotly` in it?
[bacass.zip](https://github.com/nf-core/bacass/files/3496927/bacass.zip)

**Comment by drpatelh** [comment]
That may be because you are using the `environment.yml` from the `master` branch and not the one on the `dev` branch. The file you have just edited in this PR does have these tools so it would be worth trying to pin them in that file, rebuilding the conda environment to see if it works, and then testing the pipeline using that environment. If all is well then you can push those commits here and we can merge the PR to rebuild the `Docker` container.

Also, on a side-note it is probably better to routinely execute the pipeline with either `Docker` or `Singularity` because `Conda` environment builds can change over time, and so arent entirely reproducible.

**Comment by xlinxlin** [comment]
Hi @drpatelh , I just finished a run with a conda environment which was created by the environment.yml file in `dev`, and I exported the new YML file here. 
`tqdm=4.33.0=py_0`, 
`jinja2=2.10.1=py_0`
`plotly=4.1.0=py_0`
I hope this helps.
```
name: bacass_dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - aragorn=1.2.38=h470a237_2
  - asn1crypto=0.24.0=py36_1003
  - atk=2.32.0=haf93ef1_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bandage=0.8.1=hb59a952_0
  - barrnap=0.9=2
  - bcftools=1.9=ha228f0b_4
  - bedtools=2.28.0=hdf88d34_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_8
  - biopython=1.74=py36h516909a_0
  - blast=2.9.0=pl526h979a64d_3
  - bleach=3.1.0=py_0
  - bowtie2=2.3.5=py36he860b03_0
  - bwa=0.7.17=hed695b0_6
  - bwidget=1.9.11=0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - canu=1.8=pl526h470a237_0
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - chrpath=0.16=h14c3975_1001
  - circos=0.69.8=0
  - click=7.0=py_0
  - clustalw=2.1=h6bb024c_4
  - colormath=3.0.0=py_2
  - cryptography=2.7=py36h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - eigen=3.3.7=h6bb024c_1000
  - entrez-direct=11.0=pl526_0
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=he1b5a44_1003
  - fastqc=0.11.8=1
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freebayes=1.3.1=py36h56106d0_0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - future=0.17.1=py36_1000
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_8
  - gdk-pixbuf=2.36.12=h7a26e22_1003
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_8
  - giflib=5.1.9=h516909a_0
  - glib=2.58.3=h6f030ca_1002
  - glimmerhmm=3.0.4=pl526hf484d3e_3
  - gnuplot=5.2.7=he39d25e_2
  - gobject-introspection=1.58.2=py36h5503ade_1002
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h5933667_1
  - gsl=2.5=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gtk2=2.24.32=h586f36d_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_8
  - h5py=2.9.0=nompi_py36hcafd542_1103
  - harfbuzz=2.4.0=h9f30f68_2
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - hmmer=3.2.1=hf484d3e_1
  - htslib=1.9=ha228f0b_7
  - icu=64.2=he1b5a44_0
  - idna=2.8=py36_1000
  - infernal=1.1.2=h14c3975_2
  - ipykernel=5.1.2=py36h5ca1d4c_0
  - ipython=7.7.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - joypy=0.2.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.2=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - kraken2=2.0.8_beta=pl526h6bb024c_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdb=6.1.26=hf484d3e_2000
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgd=2.2.5=h82918c6_1006
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libidn11=1.34=h1cef754_0
  - libidn2=2.1.1=h14c3975_0
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_0
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_2
  - libxslt=1.1.32=h31b3aaa_1004
  - llvm-openmp=8.0.0=hc9558a2_1
  - lz4-c=1.8.3=he1b5a44_1001
  - lzstring=1.0.4=py_1001
  - make=4.2.1=h14c3975_2004
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - minced=0.4.0=1
  - miniasm=0.3_r179=ha92aebf_0
  - minimap2=2.17=h84994c4_0
  - mistune=0.8.4=py36h14c3975_1000
  - multiqc=1.7=py_4
  - nanoget=1.8.0=py_1
  - nanomath=0.23.1=py36_0
  - nanoplot=1.23.1=py_0
  - nanoplotter=1.10.0=py_0
  - nanopolish=0.11.1=h99ef0c4_0
  - nbconvert=5.6.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - notebook=6.0.0=py36_0
  - numpy=1.17.0=py36h95a1406_0
  - openjdk=11.0.1=h516909a_1016
  - openmp=8.0.0=1
  - openssl=1.1.1c=h516909a_0
  - paml=4.9=h14c3975_4
  - pandas=0.25.0=py36hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=he7ab937_0
  - parallel=20190722=0
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pauvre=0.1.86=py_1
  - pcre=8.41=hf484d3e_1003
  - perl=5.26.2=h516909a_1006
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-array-compare=3.0.1=pl526_1
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_0
  - perl-bio-coordinate=1.007001=pl526_0
  - perl-bio-featureio=1.6.905=pl526_1
  - perl-bio-phylo=0.58=pl526_1
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_0
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_0
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl526_1
  - perl-bioperl=1.7.2=pl526_10
  - perl-bioperl-core=1.007002=pl526_1
  - perl-bioperl-run=1.007002=pl526_3
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h6bb024c_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h14c3975_0
  - perl-dbd-sqlite=1.64=pl526h516909a_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h6bb024c_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-sort=1.01=pl526_2
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-filesys-df=0.92=pl526h14c3975_3
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-io-zlib=1.10=pl526_2
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h6bb024c_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h14c3975_2
  - perl-math-round=0.07=pl526_1
  - perl-math-spline=0.02=pl526_2
  - perl-math-vecstat=0.08=pl526_1
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-format=1.75=pl526_3
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.51=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-basic=1.6611=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-sub-uplevel=0.2800=pl526h14c3975_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h14c3975_2
  - perl-test-most=0.35=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-diff=1.45=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h6bb024c_3
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pilon=1.23=1
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h516909a_1003
  - plotly=4.1.0=py_0
  - popt=1.16=h1cef754_2002
  - porechop=0.2.3_seqan2.1.1=py36h2d50403_3
  - prodigal=2.6.3=1
  - prokka=1.14.0=pl526_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycoqc=2.2.3=py_2
  - pycparser=2.19=py36_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_2
  - pyrsistent=0.15.4=py36h516909a_0
  - pysam=0.15.3=py36h5ad169c_0
  - pysocks=1.7.0=py36_0
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py36h516909a_0
  - pyzmq=18.0.2=py36h1768529_2
  - qt=5.9.7=h0c104cb_3
  - quast=5.0.2=py36pl526ha92aebf_0
  - r-base=3.5.1=hfb2a302_1010
  - r-markdown=0.9=r351h96ca727_1000
  - r-mime=0.7=r35hcdcec82_1
  - racon=1.3.2=he860b03_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - retrying=1.3.3=py_2
  - rsync=3.1.3=h84994c4_1002
  - samtools=1.9=h8571acd_11
  - scipy=1.3.1=py36h921218d_1
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - simplejson=3.16.1=py36h470a237_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - skewer=0.2.2=h2d50403_2
  - spades=3.13.1=0
  - spectra=0.0.11=py_1
  - sqlite=3.29.0=hcee41ef_0
  - statsmodels=0.10.1=py36hc1659b7_0
  - t_coffee=11.0.8=py36hea885bf_8
  - tbb=2019.7=hc9558a2_0
  - tbl2asn=25.7=0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tidyp=1.04=1
  - tk=8.6.9=hed695b0_1002
  - tktable=2.10=h555a92e_1
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.33.0=py_0
  - traitlets=4.3.2=py36_1000
  - unicycler=0.4.7=py36hdbcaa40_0
  - urllib3=1.25.3=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wget=1.20.1=h90d6eec_0
  - wheel=0.33.4=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
prefix: /home/sysgen/.conda/envs/bacass_dev

```

**Comment by drpatelh** [comment]
Great! Thanks @xlinxlin . I just wanted to make sure that there were no dependency conflicts. It appears like those package versions at the latest in Anaconda anyway.

Could you replace these lines in `environment.yml`:
```
- tqdm
- jinja2
- plotly
```

with 

```
- tqdm=4.33.0
- jinja2=2.10.1
- plotly=4.1.0
```

and push a commit to the PR please? That should be enough to get the lint tests passing because any software required by the pipeline in the `environment.yml` has to have an explicit version number.

**Comment by drpatelh** [comment]
Thanks @xlinxlin !

**Comment by drpatelh** [comment]
Let's see what happens now :drum:

**Comment by drpatelh** [comment]
The `Docker` container will be rebuilt now that we have merged the PR into `dev`. I'll check that it's built fine with the new environment when I get a moment :+1: Then the `Docker` image should be ready for you to use.

**Comment by drpatelh** [comment]
`Docker` container built without any errors and ready to use :+1:

**Comment by xlinxlin** [comment]
Great, thanks! @drpatelh

**Pull request merged**
