### PR TITLE
Bump version 2.4.0

### PR DESCRIPTION
**Pull request by Daniel-VM**
## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/bacass/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/bacass _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

## PR description

This PR prepares dev for releasing version 2.4.0.

### CODE REVIEW

**Comment by sralchemab** [comment]
Hi @Daniel-VM. When do you think you'll be releasing v2.4.0? Don't want to push, just need to know whether I wait a bit more for the next official release or work from a specific commit. Thanks in advance!

**Comment by Daniel-VM** [comment]
Hi @sralchemab,

Apologies for the delay in the version release. There's just one PR remaining before we release version 2.4.0. It should be ready by the end of this week.

**Review by d4straub — APPROVED** [review]
LGTM

**Comment by Daniel-VM** [comment]
Thanks 🙏🏾

**Pull request merged**
