### PR TITLE
Fix missing 'dev' tag in bumped version

### PR DESCRIPTION
**Pull request by Daniel-VM**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/bacass/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/bacass _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

## PR description
Just a PR fixing missing dev version by bumping **2.4.0dev**.
 
I have realized that dev version 2.4.0 didn't carry the tag "dev" since it hasn't been released yet.

### CODE REVIEW

**Comment by d4straub** [comment]
Indeed, the dev tag should be there. Usually there is a warning in nf-core lint about the missing dev tag, probably we need to be a little more careful when looking at them ;)

**Review by d4straub — APPROVED** [review]
LGTM

**Comment by Daniel-VM** [comment]
> Indeed, the dev tag should be there. Usually there is a warning in `nf-core lint` about the missing dev tag, probably we need to be a little more careful when looking at them ;)

Absolutely 😅 

> Looking at the tests, why [files_unchanged](https://nf-co.re/tools/docs/2.14.1/pipeline_lint_tests/files_unchanged) - File ignored due to lint config: .github/CONTRIBUTING.md [files_unchanged](https://nf-co.re/tools/docs/2.14.1/pipeline_lint_tests/files_unchanged) - File ignored due to lint config: .github/PULL_REQUEST_TEMPLATE.md ?

I thought nf-core/bacass didn't allow the -profile debug, but it actually does. So, this ignoring step aims to avoid nf-core linting errors while checking if those files differ from the TEMPLATE.

I am going to fix it in next PR.

**Comment by Daniel-VM** [comment]
`files_unchanged` fixed  here https://github.com/nf-core/bacass/pull/153  ;)

**Pull request merged**
