### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lborcard**
Add flye
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/bacass/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/bacass _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by Daniel-VM — COMMENTED** [review]
Please, add citations  [here](https://github.com/nf-core/bacass/blob/62655234c3e45cc3de27cffc19be36c004a33fba/subworkflows/local/utils_nfcore_bacass_pipeline/main.nf#L203) and [here](https://github.com/nf-core/bacass/blob/62655234c3e45cc3de27cffc19be36c004a33fba/subworkflows/local/utils_nfcore_bacass_pipeline/main.nf#L232)  too.

**Comment by Daniel-VM** [comment]
It would be great to have a test profile for flye in `conf/` . Ideally this test should be executed by git CI tests. See https://github.com/nf-core/bacass/pull/106#issuecomment-1803475254

**Comment by Daniel-VM** [comment]
It appears that your changes are pulling lines from master. In other words, it seems like you're pulling changes from master, merging them into your dev branch, and then pushing your dev branch into nf-core/bacass:dev. This is risky because we might overwrite newer lines in the dev branch.

My advice is to: 
1- fork github nf-core/bacas to your github ("origin")
2- pull  origin to your working directory in your local computer.
3- checkout to dev and start making changes in this dev.

once completed:
4- push your local dev branch to your origin dev
5- PR form your origin dev to nf-core/bacass:dev.

See sections Contribution overview, testing, pipeline tests in  nf-core guidelines about [contributing to an existing pipeline.](https://nf-co.re/docs/contributing/contributing_to_pipelines)

**Comment by Daniel-VM** [comment]
Careful, I have seen that you have created another branch  directly into   `nf-core/bacass` original repo. this is not the way we have to follow. New branches needs to be created in your forked repo in order to make PRs like this: `forked_repo:dev` to `nf-core_repo:dev`.

**Comment by lborcard** [comment]
> It appears that your changes are pulling lines from master. In other words, it seems like you're pulling changes from master, merging them into your dev branch, and then pushing your dev branch into nf-core/bacass:dev. This is risky because we might overwrite newer lines in the dev branch.
> 
> My advice is to: 1- fork github nf-core/bacas to your github ("origin") 2- pull origin to your working directory in your local computer. 3- checkout to dev and start making changes in this dev.
> 
> once completed: 4- push your local dev branch to your origin dev 5- PR form your origin dev to nf-core/bacass:dev.
> 
> See sections Contribution overview, testing, pipeline tests in nf-core guidelines about [contributing to an existing pipeline.](https://nf-co.re/docs/contributing/contributing_to_pipelines)



> Careful, I have seen that you have created another branch directly into `nf-core/bacass` original repo. this is not the way we have to follow. New branches needs to be created in your forked repo in order to make PRs like this: `forked_repo:dev` to `nf-core_repo:dev`.

This problem was fixed, I am now working from a fork of the bacass:dev so I wonder if there are issues from a previous version, before I changed to my fork

**Comment by lborcard** [comment]
I don't see anything coming from the master branch, I am probably missing something. 

> Careful, I have seen that you have created another branch directly into `nf-core/bacass` original repo. this is not the way we have to follow. New branches needs to be created in your forked repo in order to make PRs like this: `forked_repo:dev` to `nf-core_repo:dev`.

Yes this was my initial mistake, I am not using this branch anymore. Sorry about the inconvenience.

**Comment by lborcard** [comment]
Thanks a lot for the help, it seems that a lot of the problem come from the fact that I initially used the master branch to work on the pipeline. I will now close this add the new suggestions.

**Pull request closed without merging**
