### PR TITLE
Merging template updates 2.1

### PR DESCRIPTION
**Pull request by d4straub**
This should solve #52 . This PR is about making the pipeline work again, not adding new features.

As a byproduct, #51 is solved as well.

As far as I can see there is no test with appropriate data for running `canu`, `PycoQC`, or `nanopolish`.

## PR checklist

- [x] pull in template update 2.1 → make linting work
- [x] adapt input samplesheet
- [x] make input channels work
- [x]  check if modules exist https://github.com/nf-core/bacass/blob/dev/conf/base.config
- [x] make modules, use [conf/base.config](https://github.com/nf-core/bacass/blob/dev/conf/base.config) & [main.nf](https://github.com/nf-core/bacass/blob/dev/main.nf)
- [x] make test profile work
- [x] make all tests work
- [x] update all software to current/working version
- [x] polish output directories
- [x] update CHANGELOG
- [x] update README
- [x] update output.md
- [x] update CITATIONS
- [x] make sure NanoPolish works (not covered by tests)
- [x] make sure PyroQC works (not covered by tests)
- [x] make sure Canu works (not covered by tests)
- [x] update usage.md
- [x] add full size test data

### CODE REVIEW

**Comment by d4straub** [comment]
Unfortunately nf-core modules unicycler & spades seem both to allow only short read assembly, quite disappointing. Might have to use custom modules than. I postpone that.

**Comment by d4straub** [comment]
short read processing works.

nf-core modules that I was looking into:
- unicycler: allows only short read assembly
- Nanoplot: accepts only .fastq.gz files ( I have .fastq, could be changed)
- minimap2: unclear, nf-core tools did not allow me to install it
- kraken2: installed
- quast: installed
- prokka: could not make it work when not using valid files in "path proteins" or "path prodigal"

**Comment by d4straub** [comment]
`test_long` fails with `assembler = 'canu'` when using `input = 'https://raw.githubusercontent.com/nf-core/test-datasets/bacass/bacass_long.csv'`, because the dataset seems too small, all reads are filtered out because of insufficient overlap. I changed to `input = 'https://raw.githubusercontent.com/nf-core/test-datasets/bacass/bacass_long_miniasm.csv'` which has a much smaller subset of reads, but this seems to run really long. This might be due to canu 2.0 -> 2.1.1? 

@apeltzer was `test_long` even targeting canu? If no, no test profile seems to run canu?

Processes `nanopolish` & `medaka` are still missing.

**Comment by d4straub** [comment]
I think haven't touched in the [last commit](https://github.com/nf-core/bacass/pull/56/commits/d00f08bb5ae9902af28b31b9dadc25569b5b7e72) any part of `test_long_miniasm` but it did fail afterwards. [Here](https://github.com/nf-core/bacass/runs/3323395528) it works, but [here](https://github.com/nf-core/bacass/runs/3340074423) it fails.

**Comment by apeltzer** [comment]
Let me know if i should review / comment / aid in anything. I might have to dig into things again, as this was done a while ago but could potentially help clarifying things. The choice of tests was always an issue in this pipeline due to the size of "normal" input files for assembly and choosing subsets that at least work to some extent remained to be super challenging unfortunately... :-(

**Comment by apeltzer** [comment]
Yeah I guess DSL 1 -> 2 adds quite some changes too 😅

**Comment by d4straub** [comment]
The container of Nanopolish isn't containing `parallel` and therefore the process fails (`parallel: command not found`). I test now without `parallel` (see last commit 545763a).

**Comment by d4straub** [comment]
Hi @apeltzer , I would need suggestions/comments.
NanoPolish seems to work, real data is still running, but it passed previously failing steps. So all seems fine right now.

What I see is still lacking:
- no data in `test_full.config` yet, therefore no AWS tests or AWS results. For the sake of testing, I could add there the `test_hybrid`, would that be fine?
- unused parameters are still appearing, i.e. `igenomes`, `params.fasta`, `params.genomes`. Can I remove those or might they have any value? Right now they are not interfering, but are not used either.
- I attempted to complete the docs (were before actually incomplete), but some things might have slipped through.

Whats next when this PR is fine? I was thinking to address the most urgent matter(s) in #57 , right now I think its the structural changes. (You might remember, you and Stefan had some trouble with a bacterial assembly, this is solved with this version already, miniasm assembly produces 1 contig in correct size. But that might have not been obvious because all software combinations/options have to be specified individually, I'd recommend that by default all assemblers run based on the provided data, so that one can compare performance of all methods.)

However, it might be best to release the pipeline before those structural changes, because I might need some more weeks/months to implement it?!

**Comment by apeltzer** [comment]
> * no data in `test_full.config` yet, therefore no AWS tests or AWS results. For the sake of testing, I could add there the `test_hybrid`, would that be fine?

Yes, I think this wasn't fully there in the past when I started working on the workflow (which I also took over from Andreas Wilm in the very beginning to be honest!)

>   _edit: alternatively I could add Illumina-only data from [PRJNA563526](https://www.ncbi.nlm.nih.gov/bioproject?term=PRJNA563526) = https://pubmed.ncbi.nlm.nih.gov/32561582/, either both genomes or just one._

Both fine for me , large scale tests can be large-scale ;-) 

> * unused parameters are still appearing, i.e. `igenomes`, `params.fasta`, `params.genomes`. Can I remove those or might they have any value? Right now they are not interfering, but are not used either.

Drop everything that isn't used, this just confuses people. 

> * I attempted to complete the docs (were before actually incomplete), but some things might have slipped through.

I assume this could all benefit from some extra work on that side. Happy to help out here and there on that and check that all is there.

> Whats next when this PR is fine? I was thinking to address the most urgent matter(s) in #57 , right now I think its the structural changes. (You might remember, you and Stefan had some trouble with a bacterial assembly, this is solved with this version already, miniasm assembly produces 1 contig in correct size. But that might have not been obvious because all software combinations/options have to be specified individually, I'd recommend that by default all assemblers run based on the provided data, so that one can compare performance of all methods.)

If this is working fine, one could do it. At the moment it was more a choice of 1 option and then running multiple runs with different tools and finally comparing - but could do as you proposed yes, I agree. 

> However, it might be best to release the pipeline before those structural changes, because I might need some more weeks/months to implement it?!

Yup, a release should help address open points / issues & then moving forward with the restructure is a good idea 👍🏻

**Comment by d4straub** [comment]
Alright, all done & tested. I tested `test_full` on our cluster, but not on AWS; but I will start the AWS test using github actions once the PR is merged.

**Comment by apeltzer** [comment]
So local runs finished here too - happy to see this on dev and proceed from there 👍🏻

**Review by apeltzer — APPROVED** [review]
Looks all good but will do a final review on the `dev` to `master`as this is basically an entire rewrite of the origina DSLv1 pipeline

**Comment by d4straub** [comment]
Great, thanks!

**Pull request merged**
