### PR TITLE
Some small additions for 1.1.0 release

### PR DESCRIPTION
**Pull request by apeltzer**
- add in Medaka as alternative polishing method (50x faster!)
- cleaned up some docs

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/bacass branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/bacass)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Should be ready for reviews now @MaxUlysse @ggabernet

**Comment by apeltzer** [comment]
> Slightly confused on why process polishing became nanoplish and params skip_nanopolish became skip_polish.

I added another alternative polishing method (`medaka`) and wanted to have a generic possibility to skip polishing the assembly in the end for both cases. Thats why :-)

**Comment by apeltzer** [comment]
Labels are working perfectly now 👍

**Comment by MaxUlysse** [comment]
Can you clarify in the docs about the `dfast` config?

**Comment by apeltzer** [comment]
Done ✅

**Pull request merged**
