### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by Daniel-VM**
## PR description
This PR is for release 2.1.0

Major changes are:
	- nf-core/bacass update to nf-core tools 2.10
	- Refactor local modules into nf-core modules when possilbe (plus version update).
	- Added nf-core subworkflow for trimming and QC using FastP and fastqc, respectively
	- Added nf-validation pluging on samplesheet.
	- Added module's output statistics to MultiQC.
	- Added subworkflow for gene annotation with Bakta

More details in CHANGLEOG

> Note: You will see  two commits that bump versions >2.1.0. Those were my mistakes and there were fixed in #95 to recover v2.1.0. 

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
    - [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/bacass/tree/master/.github/CONTRIBUTING.md)
    - [X] If necessary, also make a PR on the nf-core/bacass _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [X] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by d4straub — APPROVED** [review]
Looks good to me! (but I also reviewed the individual PRs, so not a big surprise)

For a release (i.e. PR to master from dev) are 2 reviews necessary. You could post a request to get reviews in nf-core slack #request-review.

edit: additionally, required tests are also blocking the merge, I requested a change of branch protection rules in nf-core slack channel pipeline-maintainers.

**Comment by Daniel-VM** [comment]
Ok ;). Thanksss @d4straub !

**Comment by Daniel-VM** [comment]
Should I commit the new changes directly to `nf-core/bacass:dev` (my upstream) to reset the GitHub test? Or would it be better to push to my fork (dev) and then merge the forked dev into nf-core/bacass:dev?

**Comment by d4straub** [comment]
Unfortunately it didnt update the tests, so it seems to need a push. Sorry (but would have been the quickest fix...).

**Comment by Daniel-VM** [comment]
I see 😅, we had to try it. I am going to add a new commit and see if it updates the tests.

**Comment by d4straub** [comment]
Hm, but `Run pipeline with test data` is still expected but it shouldn't!!! I assume the branch protection isn't fixed yet... :'(

**Pull request merged**
